export const facts = [
  "Your heart beats around 100,000 times a day.",
  "Octopuses have three hearts. Honestly, showing off.",
  "Yawning is contagious. You probably just yawned reading this.",
  "Bananas are technically berries. Strawberries technically aren't. Biology is chaotic.",
  "Your body contains trillions of microorganisms. You're basically a tiny ecosystem.",
  "Somewhere, someone is probably reading this while forgetting to drink water.",
  "Your bones are about five times stronger than steel, gram for gram.",
  "Laughing for 15 minutes can burn roughly the same calories as a 10-minute walk.",
  "Your nose can remember around 50,000 different scents.",
  "A single sneeze can travel faster than 150 km/h.",
  "You blink around 15-20 times a minute — that's about 20,000 times a day.",
  "Your skin fully replaces itself roughly every 27 days.",
  "A group of flamingos is called a 'flamboyance.'",
  "Honey never spoils. Archaeologists have found edible honey in ancient Egyptian tombs.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "Your brain uses about 20% of your body's total energy, despite being ~2% of your body weight.",
  "Wombat poop is cube-shaped. Nobody's entirely sure why.",
  "The Eiffel Tower grows about 15cm taller in summer due to heat expansion.",
  "A bolt of lightning is hotter than the surface of the sun.",
  "Cows have best friends and get stressed when separated from them.",
  "Your tongue print is as unique as your fingerprint.",
  "Sharks existed before trees.",
  "Butterflies taste with their feet.",
  "There are more possible chess games than atoms in the observable universe.",
  "A shrimp's heart is located in its head.",
  "Elephants are one of the few animals that can recognize themselves in a mirror.",
  "You can't hum while holding your nose closed. Try it.",
  "The shortest war in recorded history lasted about 38 minutes.",
  "Some turtles can breathe through their butts. Truly.",
  "Hot water can freeze faster than cold water under certain conditions — it's called the Mpemba effect.",
  "A single cloud can weigh over a million pounds.",
  "Your left lung is smaller than your right one, to make room for your heart.",
  "Koalas have fingerprints almost identical to humans.",
  "Venus is the only planet that spins clockwise.",
  "Peanuts aren't nuts — they're legumes.",
  "Astronauts get slightly taller in space due to spinal decompression.",
  "The inventor of the frisbee was turned into a frisbee after he died — his ashes were molded into discs.",
  "Some cats are actually allergic to humans.",
  "The dot over a lowercase 'i' or 'j' has a name: it's called a tittle.",
  "Humans share about 60% of their DNA with bananas.",
  "A day on Venus is longer than a year on Venus.",
  "Wearing headphones for just an hour can increase the bacteria in your ear by 700 times.",
  "The Great Wall of China isn't actually visible from space with the naked eye — that's a myth.",
  "Starfish don't have brains.",
  "Your stomach gets an entirely new lining every few days so it doesn't digest itself.",
  "A group of crows is called a 'murder.'",
  "Polar bears have black skin under their white fur.",
  "The longest recorded flight of a chicken is about 13 seconds.",
  "Human ears and noses never stop growing, technically, throughout life.",
  "Some jellyfish are biologically immortal.",
  "The world's oldest known recipe is for beer.",
  "You have a muscle in your ear that's the smallest in your body — the stapedius.",
  "It's impossible to lick your own elbow — well, almost everyone finds it impossible.",
  "An octopus can taste through its arms.",
  "A day on Mars is only about 40 minutes longer than a day on Earth.",
  "Cleopatra lived closer in time to the moon landing than to the building of the Great Pyramid.",
  "There's a species of jellyfish called the immortal jellyfish that can revert to an earlier life stage.",
  "Your body produces about 25 million new cells every second.",
  "Dolphins have names for each other — unique signature whistles.",
  "The average person walks the equivalent of three times around the world in their lifetime.",
  "Onions make you cry because of a chemical reaction that irritates your eyes, not because they're sad.",
  "A hummingbird's heart can beat over 1,200 times a minute.",
  "The inventor of the microwave accidentally discovered it while working on radar technology.",
  "Sloths can hold their breath longer than dolphins can.",
  "Your feet have about 250,000 sweat glands combined.",
  "Owls can't move their eyeballs — that's why they rotate their whole head.",
  "The first oranges weren't orange — they were green.",
  "Human bones are constantly rebuilding themselves throughout your life.",
  "A snail can sleep for up to three years.",
  "There are more stars in the universe than grains of sand on every beach on Earth.",
  "Your ears secrete more earwax when you're stressed or afraid.",
  "The Mona Lisa has no eyebrows — it was a beauty trend at the time it was painted.",
  "Kangaroos can't walk backwards.",
  "Some plants can 'hear' themselves being eaten and respond by producing defensive chemicals.",
  "It technically rains diamonds on Jupiter and Saturn.",
  "A blue whale's heart alone can weigh as much as a small car.",
  "Your body is constantly making new red blood cells — about 2 million every second.",
  "Penguins propose to their mates with a pebble.",
  "The average cumulus cloud weighs about as much as 100 elephants.",
  "Humans are the only animals known to blush.",
  "A crocodile can't stick its tongue out.",
  "There's enough DNA in your body to stretch from the Earth to the sun and back over 300 times.",
  "The unicorn is Scotland's national animal.",
  "Bees can recognize individual human faces.",
  "The 'new car smell' is actually a mix of chemicals off-gassing from materials inside the car.",
  "Giraffes only need to sleep about 30 minutes to 2 hours a day.",
  "Your smell and taste are deeply linked — most of what you 'taste' is actually smell.",
  "A rhinoceros's horn is made of the same protein as your hair and nails: keratin.",
  "The moon is slowly drifting away from Earth, about 3.8 cm per year.",
  "Some species of bamboo grow almost a meter in a single day.",
  "Human beings are bioluminescent, but the glow is too faint for the naked eye to see.",
  "Squirrels forget where they bury a large portion of their nuts.",
  "A single strand of spaghetti is called a 'spaghetto.'",
  "The heart of a shrimp is located near its head, not its chest.",
  "Turtles can feel through their shells — it's connected to their nervous system.",
  "It's estimated your body has around 37 trillion cells.",
  "A woodpecker can peck a tree up to 20 times per second.",
  "There's a real phenomenon called 'brain freeze' caused by rapid cooling of blood vessels in your palate.",
  "Otters use rocks as tools to crack open shellfish.",
  "The average human sneeze can send droplets out at over 100 km/h.",
  "Chameleons change color mainly to communicate, not just to camouflage.",
  "The human eye can distinguish about 10 million different colors.",
  "Sea horses are one of the only species where the males carry the babies.",
  "The word 'quarantine' comes from the Italian for '40 days.'",
  "Your body temperature naturally dips slightly in the afternoon, which can make you feel sleepy.",
  "Flamingos are born gray — their pink color comes from pigments in the food they eat.",
  "A group of pandas is called an 'embarrassment.'",
  "Your left and right lungs don't have the same number of lobes.",
  "It takes about 8 minutes and 20 seconds for sunlight to reach Earth.",
  "Some frogs can be frozen solid over winter and thaw out alive in spring.",
  "The human body has enough iron in it to make a small nail.",
  "A rainbow can technically be a full circle — you just usually only see the top half from the ground.",
  "Cats can't taste sweetness — they're missing the taste receptor for it.",
  "There are more possible iterations of a shuffled deck of cards than there are seconds since the universe began.",
  "The average person spends about 6 months of their life waiting for red lights to turn green.",
]