export const motivationalMessages = [
  "You're doing better than you think. 🌿",
  "Taking care of yourself is never a waste of time.",
  "One step at a time — that's still progress.",
  "It's okay to ask for help. That's what we're here for.",
  "You showed up today. That counts for something.",
  "Small steps count. You're allowed to take them slowly.",
  "You don't have to have it all figured out today.",
  "Rest is productive too.",
  "You're allowed to prioritize yourself.",
  "This moment is temporary — you're doing okay.",
  "Progress isn't always loud. Sometimes it's just showing up.",
  "Be as kind to yourself as you'd be to a friend.",
  "You're not behind. You're exactly where you need to be.",
  "It's okay to not be okay today.",
  "Drink some water. Seriously, right now. 💧",
  "You've gotten through every hard day so far.",
  "Asking questions is a sign of strength, not weakness.",
  "You're allowed to take up space and ask for care.",
  "One good decision today is still a win.",
  "Healing isn't linear, and that's completely normal.",
  "You're more resilient than you give yourself credit for.",
  "Today doesn't have to be perfect to be good.",
  "You made it this far — that's worth noticing.",
  "Slow progress is still progress.",
  "Take the breath. You've earned it.",
]